import { useEffect, useState } from 'react';
import { Activity, ArrowRight, Calendar, CheckCircle2, ChevronLeft, Clock3, Dumbbell, History, LineChart, Play, Plus, Square, Target, Trash2 } from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { abandonMemberSession, completeMemberSession, createMemberSet, deleteMemberSet, getMemberCurrent, getMemberProgress, getMemberSchedule, getMemberSession, listMemberSchedules, listMemberSessions, startMemberSession } from '../../services/memberWorkoutApi';
import type { MemberCurrent, MemberProgress, MemberSchedule, MemberSession, MemberSessionExercise } from '../../types/memberWorkout';

const dateLabel = (value:string) => new Date(`${value.slice(0,10)}T00:00:00`).toLocaleDateString('vi-VN', { weekday:'short', day:'2-digit', month:'2-digit' });
const timeLabel = (value:string) => new Date(value).toLocaleString('vi-VN', { dateStyle:'short', timeStyle:'short' });
const errorText = (error:unknown) => { const candidate = error as { response?:{data?:{message?:string}} }; return candidate.response?.data?.message || 'Không thể tải dữ liệu workout.'; };
const Page = ({ title, description, children, actions }:{title:string;description:string;children:React.ReactNode;actions?:React.ReactNode}) => <div className="dashboard-page"><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.18em] text-emerald-400">MEMBER WORKOUT</p><h1 className="mt-2 text-3xl font-semibold text-white">{title}</h1><p className="mt-2 max-w-2xl text-sm text-slate-400">{description}</p></div>{actions}</div>{children}</div>;
const Loading = () => <div className="dashboard-panel"><div className="panel-state"><Activity size={18}/> Đang tải dữ liệu...</div></div>;
const ErrorBox = ({ message }:{message:string}) => <div className="dashboard-panel border-red-400/30"><div className="panel-state text-red-200">{message}</div></div>;
const Status = ({ value }:{value:string}) => <span className="rounded-full bg-slate-800 px-2.5 py-1 text-xs text-slate-300">{value}</span>;

export function MemberWorkoutHomePage() {
  const [data,setData] = useState<MemberCurrent|null>(null); const [error,setError] = useState('');
  useEffect(() => { getMemberCurrent().then(setData).catch(error => setError(errorText(error))); }, []);
  if (error) return <Page title="Workouts" description="Assignment, lịch và buổi tập của riêng bạn."><ErrorBox message={error}/></Page>;
  if (!data) return <Page title="Workouts" description="Assignment, lịch và buổi tập của riêng bạn."><Loading/></Page>;
  return <Page title="Workouts" description="Bắt đầu đúng lịch, ghi set theo snapshot Coach giao và theo dõi tiến độ thật." actions={<Link className="primary-button inline-flex items-center gap-2" to="/workouts/schedule"><Calendar size={16}/> Mở schedule</Link>}>
    {data.activeSession && <div className="mb-6 rounded-2xl border border-emerald-400/30 bg-emerald-400/10 p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs uppercase tracking-wider text-emerald-300">Đang tập</p><h2 className="mt-1 text-xl font-semibold text-white">{data.activeSession.program.name}</h2><p className="mt-1 text-sm text-slate-300">{data.activeSession.exercises.length} exercises · bắt đầu {timeLabel(data.activeSession.started_at)}</p></div><Link className="primary-button inline-flex items-center gap-2" to={`/workouts/sessions/${data.activeSession.id}`}>Tiếp tục <ArrowRight size={16}/></Link></div></div>}
    <div className="grid gap-4 md:grid-cols-3"><Link to="/workouts/program" className="dashboard-panel block hover:border-emerald-400/40"><Dumbbell className="text-emerald-300" size={20}/><h2 className="mt-4 font-semibold text-white">Program hiện tại</h2><p className="mt-1 text-sm text-slate-400">{data.assignment?.program_name || 'Chưa có assignment active'}</p></Link><Link to="/workouts/sessions" className="dashboard-panel block hover:border-emerald-400/40"><History className="text-sky-300" size={20}/><h2 className="mt-4 font-semibold text-white">Session history</h2><p className="mt-1 text-sm text-slate-400">Xem lại các buổi đã hoàn thành hoặc bỏ qua.</p></Link><Link to="/progress" className="dashboard-panel block hover:border-emerald-400/40"><LineChart className="text-amber-300" size={20}/><h2 className="mt-4 font-semibold text-white">Progress</h2><p className="mt-1 text-sm text-slate-400">Volume, duration và completion rate.</p></Link></div>
    <div className="dashboard-panel mt-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold text-white">Lịch sắp tới</h2><p className="mt-1 text-sm text-slate-400">Timezone: {data.assignment?.schedule_timezone || '—'}</p></div><Link className="text-sm text-emerald-300" to="/workouts/schedule">Xem tất cả</Link></div>{data.upcomingSchedules.length===0?<div className="panel-state mt-5">Chưa có schedule. Coach cần tạo lịch cho assignment active.</div>:<div className="mt-4 grid gap-3 md:grid-cols-2">{data.upcomingSchedules.slice(0,6).map(item=><Link className="quick-action" key={item.id} to={`/workouts/schedule/${item.id}`}><Calendar size={18}/><span><strong>{dateLabel(item.scheduled_date)} · {item.day_title}</strong><small>{data.assignment?.program_name} · <Status value={item.status}/></small></span><ArrowRight size={16}/></Link>)}</div>}</div>
  </Page>;
}

export function MemberWorkoutProgramPage() {
  const [data,setData] = useState<MemberCurrent|null>(null); const [error,setError] = useState('');
  useEffect(() => { getMemberCurrent().then(setData).catch(error => setError(errorText(error))); }, []);
  return <Page title="Program hiện tại" description="Đây là plan thuộc assignment active. Snapshot execution chỉ được tạo khi bạn Start Session." actions={<Link className="secondary-button inline-flex items-center gap-2" to="/workouts"><ChevronLeft size={16}/> Workouts</Link>}>{error?<ErrorBox message={error}/>:!data?<Loading/>:!data.program||!data.assignment?<div className="dashboard-panel"><div className="panel-state">Chưa có assignment active.</div></div>:<div className="space-y-4"><div className="dashboard-panel"><p className="text-xs uppercase tracking-wider text-emerald-300">{data.assignment.coach_name} · {data.assignment.difficulty}</p><h2 className="mt-2 text-2xl font-semibold text-white">{data.assignment.program_name}</h2><p className="mt-2 text-sm text-slate-400">{data.assignment.program_description||'Coach chưa thêm mô tả.'}</p></div>{data.program.days.map(day=><section className="dashboard-panel" key={day.id}><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-xs text-emerald-300">Week {day.week_number} · Day {day.day_number}</p><h2 className="mt-1 text-lg font-semibold text-white">{day.title}</h2></div><Status value={`${day.exercises.length} exercises`}/></div><div className="mt-4 space-y-2">{day.exercises.map(exercise=><div className="rounded-xl border border-slate-800 p-3" key={exercise.program_exercise_id}><div className="flex items-center justify-between gap-3"><strong className="text-white">{exercise.exercise_name}</strong><span className="text-xs text-slate-500">#{exercise.sort_order+1}</span></div><p className="mt-2 text-sm text-slate-400">{exercise.target_sets?`${exercise.target_sets} sets · `:''}{exercise.target_reps_min||exercise.target_reps_max?`${exercise.target_reps_min||''}-${exercise.target_reps_max||''} reps`:exercise.target_duration_seconds?`${exercise.target_duration_seconds}s`:''}{exercise.target_weight!=null?` · ${exercise.target_weight} kg`:''}</p>{exercise.coach_note&&<p className="mt-2 text-xs text-slate-500">Coach note: {exercise.coach_note}</p>}</div>)}</div></section>)}</div>}</Page>;
}

export function MemberWorkoutSchedulePage() {
  const [items,setItems] = useState<MemberSchedule[]>([]); const [error,setError] = useState(''); const [loading,setLoading] = useState(true); const navigate = useNavigate();
  useEffect(() => { listMemberSchedules({page:1,limit:50}).then(result=>setItems(result.items)).catch(error=>setError(errorText(error))).finally(()=>setLoading(false)); }, []);
  const start = async (scheduleId:number) => { try { const session=await startMemberSession(scheduleId); navigate(`/workouts/sessions/${session.id}`); } catch(error) { setError(errorText(error)); } };
  return <Page title="Schedule" description="Chỉ schedule thuộc assignment của bạn. Backend kiểm tra ngày hiện tại theo IANA timezone khi Start." actions={<Link className="secondary-button inline-flex items-center gap-2" to="/workouts"><ChevronLeft size={16}/> Workouts</Link>}>{error&&<ErrorBox message={error}/>} {loading?<Loading/>:items.length===0?<div className="dashboard-panel"><div className="panel-state"><Calendar size={18}/> Chưa có schedule.</div></div>:<div className="grid gap-3">{items.map(item=><div className="dashboard-panel flex flex-wrap items-center justify-between gap-4" key={item.id}><div><p className="text-xs text-emerald-300">{dateLabel(item.scheduled_date)} · Week {item.week_number} Day {item.day_number}</p><h2 className="mt-1 font-semibold text-white">{item.program_name} · {item.day_title}</h2><p className="mt-1 text-sm text-slate-400">{item.schedule_timezone} · <Status value={item.status}/></p></div><div className="flex gap-2"><Link className="secondary-button" to={`/workouts/schedule/${item.id}`}>Chi tiết</Link>{item.status==='SCHEDULED'&&<button className="primary-button inline-flex items-center gap-2" onClick={()=>void start(item.id)}><Play size={15}/> Start</button>}</div></div>)}</div>}</Page>;
}

export function MemberWorkoutScheduleDetailPage() {
  const { scheduleId } = useParams(); const [item,setItem] = useState<MemberSchedule|null>(null); const [error,setError] = useState(''); const navigate = useNavigate();
  useEffect(() => { if(scheduleId)getMemberSchedule(Number(scheduleId)).then(setItem).catch(error=>setError(errorText(error))); }, [scheduleId]);
  const start = async () => { if(!scheduleId)return; try { const session=await startMemberSession(Number(scheduleId)); navigate(`/workouts/sessions/${session.id}`); } catch(error) { setError(errorText(error)); } };
  return <Page title="Schedule detail" description="Kiểm tra snapshot target trước khi bắt đầu buổi tập." actions={<Link className="secondary-button inline-flex items-center gap-2" to="/workouts/schedule"><ChevronLeft size={16}/> Schedule</Link>}>{error?<ErrorBox message={error}/>:!item?<Loading/>:<div className="dashboard-panel"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs text-emerald-300">{dateLabel(item.scheduled_date)} · {item.schedule_timezone}</p><h2 className="mt-2 text-2xl font-semibold text-white">{item.program_name} · {item.day_title}</h2></div><div className="flex items-center gap-2"><Status value={item.status}/>{item.status==='SCHEDULED'&&<button className="primary-button inline-flex items-center gap-2" onClick={()=>void start()}><Play size={15}/> Start Session</button>}</div></div><div className="mt-6 space-y-2">{(item as MemberSchedule & {exercises?:MemberSessionExercise[]}).exercises?.map(exercise=><div className="rounded-xl border border-slate-800 p-3" key={exercise.program_exercise_id}><strong className="text-white">{exercise.exercise_name}</strong><p className="mt-1 text-sm text-slate-400">Target: {exercise.target_sets||'—'} sets · {exercise.target_reps_min||exercise.target_reps_max?`${exercise.target_reps_min||''}-${exercise.target_reps_max||''} reps`:exercise.target_duration_seconds?`${exercise.target_duration_seconds}s`:'—'}</p></div>)}</div></div>}</Page>;
}

export function MemberWorkoutSessionsPage() {
  const [items,setItems] = useState<MemberSession[]>([]); const [error,setError] = useState(''); const [loading,setLoading] = useState(true);
  useEffect(() => { listMemberSessions({page:1,limit:50}).then(result=>setItems(result.items as unknown as MemberSession[])).catch(error=>setError(errorText(error))).finally(()=>setLoading(false)); }, []);
  return <Page title="Session history" description="Lịch sử execution của riêng bạn, bao gồm snapshot và set summary." actions={<Link className="secondary-button inline-flex items-center gap-2" to="/workouts"><ChevronLeft size={16}/> Workouts</Link>}>{error?<ErrorBox message={error}/>:loading?<Loading/>:items.length===0?<div className="dashboard-panel"><div className="panel-state"><History size={18}/> Chưa có session.</div></div>:<div className="grid gap-3">{items.map(item=><Link className="dashboard-panel block hover:border-emerald-400/40" key={item.id} to={`/workouts/sessions/${item.id}`}><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold text-white">{item.program.name}</h2><p className="mt-1 text-sm text-slate-400">{item.schedule?.scheduled_date||'—'} · {timeLabel(item.started_at)}</p></div><Status value={item.status}/></div></Link>)}</div>}</Page>;
}

function SetEditor({ sessionId, exercise, onSaved }:{sessionId:number;exercise:MemberSessionExercise;onSaved:()=>void}) {
  const [setNumber,setSetNumber] = useState(exercise.sets.length+1); const [reps,setReps] = useState(''); const [weight,setWeight] = useState(''); const [busy,setBusy] = useState(false); const [error,setError] = useState('');
  const add = async () => { setBusy(true); setError(''); try { await createMemberSet(sessionId,exercise.session_exercise_id,{set_number:setNumber,reps:reps===''?null:Number(reps),weight_kg:weight===''?null:Number(weight),completed:true}); setSetNumber(value=>value+1); setReps(''); setWeight(''); onSaved(); } catch(error) { setError(errorText(error)); } finally { setBusy(false); } };
  return <div className="mt-4 rounded-xl border border-slate-800 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-medium text-white">Set logs</h3><span className="text-xs text-slate-500">{exercise.sets.filter(item=>item.completed).length} completed</span></div><div className="mt-3 space-y-2">{exercise.sets.map(item=><div className="flex flex-wrap items-center justify-between gap-2 rounded-lg bg-slate-900/70 px-3 py-2 text-sm" key={item.id}><span className="text-slate-300">Set {item.set_number}</span><span className="text-slate-400">{item.reps??'—'} reps · {item.weight_kg??'—'} kg</span><span className={item.completed?'text-emerald-300':'text-slate-500'}>{item.completed?'Completed':'Draft'}</span><button className="text-slate-500 hover:text-red-300" title="Xóa set" onClick={()=>void deleteMemberSet(sessionId,exercise.session_exercise_id,item.id).then(onSaved).catch(error=>setError(errorText(error)))}><Trash2 size={15}/></button></div>)}</div><div className="mt-3 grid gap-2 sm:grid-cols-[5rem_1fr_1fr_auto]"><input aria-label="Set number" className="input" type="number" min={1} value={setNumber} onChange={event=>setSetNumber(Number(event.target.value))}/><input aria-label="Reps" className="input" type="number" min={0} placeholder="Reps" value={reps} onChange={event=>setReps(event.target.value)}/><input aria-label="Weight kg" className="input" type="number" min={0} step="0.01" placeholder="Weight kg" value={weight} onChange={event=>setWeight(event.target.value)}/><button className="primary-button inline-flex items-center justify-center gap-2" disabled={busy} onClick={()=>void add()}><Plus size={15}/> Log</button></div>{error&&<p className="mt-2 text-xs text-red-300">{error}</p>}</div>;
}

export function MemberWorkoutSessionDetailPage() {
  const { sessionId } = useParams(); const [item,setItem] = useState<MemberSession|null>(null); const [error,setError] = useState(''); const [busy,setBusy] = useState(false); const navigate = useNavigate();
  const load = () => { if(sessionId)getMemberSession(Number(sessionId)).then(setItem).catch(error=>setError(errorText(error))); };
  useEffect(load,[sessionId]);
  const finish = async (action:'complete'|'abandon') => { if(!sessionId)return; setBusy(true); try { const next=action==='complete'?await completeMemberSession(Number(sessionId)):await abandonMemberSession(Number(sessionId)); setItem(next); } catch(error) { setError(errorText(error)); } finally { setBusy(false); } };
  return <Page title="Workout session" description="Snapshot immutable; set logs chỉ được ghi khi session đang IN_PROGRESS." actions={<button className="secondary-button inline-flex items-center gap-2" onClick={()=>navigate('/workouts/sessions')}><ChevronLeft size={16}/> History</button>}>{error&&<ErrorBox message={error}/>} {!item&&!error?<Loading/>:item&&<><div className="dashboard-panel"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-wider text-emerald-300">{item.schedule.day_title}</p><h2 className="mt-2 text-2xl font-semibold text-white">{item.program.name}</h2><p className="mt-1 text-sm text-slate-400">Started {timeLabel(item.started_at)} · {item.schedule.scheduled_date}</p></div><div className="flex flex-wrap items-center gap-2"><Status value={item.status}/>{item.status==='IN_PROGRESS'&&<><button className="primary-button inline-flex items-center gap-2" disabled={busy} onClick={()=>void finish('complete')}><CheckCircle2 size={15}/> Complete</button><button className="secondary-button inline-flex items-center gap-2" disabled={busy} onClick={()=>void finish('abandon')}><Square size={15}/> Abandon</button></>}</div></div></div><div className="mt-6 space-y-4">{item.exercises.map(exercise=><section className="dashboard-panel" key={exercise.session_exercise_id}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs text-slate-500">Exercise {exercise.sort_order+1}</p><h2 className="mt-1 text-lg font-semibold text-white">{exercise.exercise_name}</h2></div><Target className="text-emerald-300" size={18}/></div><p className="mt-2 text-sm text-slate-400">Target: {exercise.target_sets||'—'} sets · {exercise.target_reps_min||exercise.target_reps_max?`${exercise.target_reps_min||''}-${exercise.target_reps_max||''} reps`:exercise.target_duration_seconds?`${exercise.target_duration_seconds}s`:'—'}{exercise.target_weight!=null?` · ${exercise.target_weight} kg`:''}</p>{item.status==='IN_PROGRESS'&&<SetEditor sessionId={item.id} exercise={exercise} onSaved={load}/>} {item.status!=='IN_PROGRESS'&&<div className="mt-4 space-y-2">{exercise.sets.map(set=><div className="text-sm text-slate-400" key={set.id}>Set {set.set_number}: {set.reps??'—'} reps · {set.weight_kg??'—'} kg · {set.completed?'completed':'not completed'}</div>)}</div>}</section>)}</div></>}</Page>;
}

function ProgressView({ data, title }:{data:MemberProgress;title:string}) { return <Page title={title} description="Chỉ dữ liệu execution của tài khoản này; volume = completed reps × weight." actions={<Link className="secondary-button inline-flex items-center gap-2" to="/workouts"><ChevronLeft size={16}/> Workouts</Link>}><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div className="metric-card metric-blue"><span>Completed sessions</span><strong>{data.completed_sessions}</strong></div><div className="metric-card metric-lime"><span>Total duration</span><strong>{Math.round(data.total_duration/60)} min</strong></div><div className="metric-card metric-amber"><span>Training volume</span><strong>{data.training_volume}</strong></div><div className="metric-card metric-slate"><span>Completion rate</span><strong>{data.completion_rate===null?'—':`${data.completion_rate.toFixed(1)}%`}</strong></div></div><div className="mt-6 grid gap-4 lg:grid-cols-2"><div className="dashboard-panel"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold text-white">Recent sessions</h2><Link className="text-sm text-emerald-300" to="/progress/sessions">View all</Link></div>{data.recent_sessions.length===0?<div className="panel-state mt-4">Chưa có completed session.</div>:<div className="mt-4 space-y-2">{data.recent_sessions.map(session=><Link className="quick-action" key={session.id} to={`/workouts/sessions/${session.id}`}><Clock3 size={17}/><span><strong>{session.program.name}</strong><small>{session.schedule?.scheduled_date||'—'} · {Math.round((session.total_duration_seconds||0)/60)} min</small></span></Link>)}</div>}</div><div className="dashboard-panel"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold text-white">Exercise progress</h2><Link className="text-sm text-emerald-300" to="/progress/exercises/summary">Details</Link></div>{data.exercise_history.length===0?<div className="panel-state mt-4">Chưa có set completed.</div>:<div className="mt-4 space-y-2">{data.exercise_history.slice(0,8).map(exercise=><div className="flex items-center justify-between gap-3 rounded-xl border border-slate-800 p-3" key={exercise.exercise_id}><span><strong className="block text-sm text-white">{exercise.exercise_name}</strong><small className="text-xs text-slate-500">{exercise.completed_sets} sets · {exercise.total_reps} reps</small></span><span className="text-sm text-emerald-300">{exercise.training_volume}</span></div>)}</div>}</div></div></Page>; }

export function MemberProgressPage() { const [data,setData] = useState<MemberProgress|null>(null); const [error,setError] = useState(''); useEffect(()=>{getMemberProgress().then(setData).catch(error=>setError(errorText(error)));},[]); return error?<Page title="Progress" description="Progress execution của riêng bạn."><ErrorBox message={error}/></Page>:!data?<Page title="Progress" description="Progress execution của riêng bạn."><Loading/></Page>:<ProgressView data={data} title="Progress"/>; }
export function MemberProgressSessionsPage() { const [data,setData] = useState<MemberProgress|null>(null); const [error,setError] = useState(''); useEffect(()=>{getMemberProgress().then(setData).catch(error=>setError(errorText(error)));},[]); return error?<Page title="Progress sessions" description="Các session đã hoàn thành."><ErrorBox message={error}/></Page>:!data?<Page title="Progress sessions" description="Các session đã hoàn thành."><Loading/></Page>:<ProgressView data={{...data,recent_sessions:data.recent_sessions}} title="Progress sessions"/>; }
export function MemberProgressExercisesPage() { const [data,setData] = useState<MemberProgress|null>(null); const [error,setError] = useState(''); useEffect(()=>{getMemberProgress().then(setData).catch(error=>setError(errorText(error)));},[]); return error?<Page title="Exercise progress" description="Tổng hợp set completed theo exercise."><ErrorBox message={error}/></Page>:!data?<Page title="Exercise progress" description="Tổng hợp set completed theo exercise."><Loading/></Page>:<ProgressView data={data} title="Exercise progress"/>; }
