import { getPool,sql } from '../../config/database';
import { AppError } from '../../middleware/errorHandler';
import { productOwnershipService } from './product-ownership.service';
type Filters={page:number;limit:number;search?:string;status?:'active'|'inactive';sort:'created_desc'|'created_asc'|'name_asc'|'name_desc'};
export const sellerProductsService={
 async list(userId:number,f:Filters){const shop=await productOwnershipService.resolveSellerShop(userId);const pool=await getPool();const req=pool.request().input('shopId',sql.Int,shop.id).input('offset',sql.Int,(f.page-1)*f.limit).input('limit',sql.Int,f.limit);const clauses=['p.shop_id=@shopId'];if(f.search){req.input('search',sql.NVarChar(202),`%${f.search}%`);clauses.push('(p.product_name LIKE @search OR EXISTS(SELECT 1 FROM dbo.ProductVariants sv WHERE sv.product_id=p.id AND sv.sku LIKE @search))');}if(f.status)clauses.push(`p.is_active=${f.status==='active'?1:0}`);const order={created_desc:'p.created_at DESC',created_asc:'p.created_at ASC',name_asc:'p.product_name ASC',name_desc:'p.product_name DESC'}[f.sort];const r=await req.query(`SELECT p.id,p.product_name name,p.slug,p.is_active isActive,p.created_at createdAt,p.updated_at updatedAt,b.id brandId,b.name brand,c.id categoryId,c.name category,
 (SELECT COUNT(*) FROM dbo.ProductVariants v WHERE v.product_id=p.id) variantCount,
 (SELECT SUM(i.available) FROM dbo.ProductVariants v JOIN dbo.Inventory i ON i.variant_id=v.id WHERE v.product_id=p.id) availableInventory,
 dv.price,dv.sale_price salePrice,pi.image_url primaryImage,COUNT_BIG(*) OVER() total
 FROM dbo.Products p LEFT JOIN dbo.Brands b ON b.id=p.brand_id LEFT JOIN dbo.Categories c ON c.id=p.category_id
 OUTER APPLY(SELECT TOP 1 price,sale_price FROM dbo.ProductVariants WHERE product_id=p.id ORDER BY is_default DESC,id)dv
 OUTER APPLY(SELECT TOP 1 image_url FROM dbo.ProductImages WHERE product_id=p.id ORDER BY is_primary DESC,sort_order,id)pi
 WHERE ${clauses.join(' AND ')} ORDER BY ${order},p.id DESC OFFSET @offset ROWS FETCH NEXT @limit ROWS ONLY`);
 return{items:r.recordset.map(x=>({...x,isActive:Boolean(x.isActive)})),shop,page:f.page,limit:f.limit,total:Number(r.recordset[0]?.total??0)};},
 async detail(userId:number,productId:number){await productOwnershipService.assertSellerOwnsProduct(productId,userId);const pool=await getPool();const base=await pool.request().input('id',sql.Int,productId).query(`SELECT p.id,p.product_name name,p.slug,p.description,p.specifications,p.is_active isActive,p.created_at createdAt,p.updated_at updatedAt,b.id brandId,b.name brand,c.id categoryId,c.name category,s.id shopId,s.name shopName,s.slug shopSlug,s.status shopStatus,s.is_verified shopVerified FROM dbo.Products p JOIN dbo.Shops s ON s.id=p.shop_id LEFT JOIN dbo.Brands b ON b.id=p.brand_id LEFT JOIN dbo.Categories c ON c.id=p.category_id WHERE p.id=@id`);if(!base.recordset[0])throw new AppError(404,'Product not found');const[variants,images]=await Promise.all([pool.request().input('id',sql.Int,productId).query(`SELECT v.id,v.variant_name variantName,v.sku,v.price,v.sale_price salePrice,v.is_active isActive,v.is_default isDefault,i.id inventoryId,i.on_hand onHand,i.reserved,i.available,i.low_stock_threshold lowStockThreshold FROM dbo.ProductVariants v JOIN dbo.Inventory i ON i.variant_id=v.id WHERE v.product_id=@id ORDER BY v.is_default DESC,v.id`),pool.request().input('id',sql.Int,productId).query(`SELECT id,image_url imageUrl,alt_text altText,is_primary isPrimary,sort_order sortOrder FROM dbo.ProductImages WHERE product_id=@id ORDER BY is_primary DESC,sort_order,id`)]);const row=base.recordset[0];return{...row,isActive:Boolean(row.isActive),shop:{id:row.shopId,name:row.shopName,slug:row.shopSlug,status:row.shopStatus,isVerified:Boolean(row.shopVerified)},variants:variants.recordset.map(v=>({...v,isActive:Boolean(v.isActive),isDefault:Boolean(v.isDefault)})),images:images.recordset.map(i=>({...i,isPrimary:Boolean(i.isPrimary)}))};}
};
