import { useCallback, useEffect, useMemo, useState } from 'react';
import { Calendar, Check, Clock, Loader2, UserCircle, X } from 'lucide-react';
import { Link } from 'react-router-dom';
import { cancelCoachBooking, completeBooking, confirmBooking, getCoachAppointments, markBookingNoShow, type Booking, type BookingStatus } from '../../services/bookings';

const label: Record<BookingStatus, string> = { pending: 'Yêu cầu mới', confirmed: 'Đã xác nhận', completed: 'Đã hoàn thành', cancelled: 'Đã hủy', no_show: 'No-show' };
const tone: Record<BookingStatus, string> = { pending: 'bg-amber-500/15 text-amber-300', confirmed: 'bg-emerald-500/15 text-emerald-300', completed: 'bg-blue-500/15 text-blue-300', cancelled: 'bg-slate-700 text-slate-400', no_show: 'bg-red-500/15 text-red-300' };

function AppointmentRow({ booking, onAction }: { booking: Booking; onAction: (id: number, status: Exclude<BookingStatus, 'pending'>) => Promise<void> }) {
  const [busy, setBusy] = useState(false);
  const action = async (status: Exclude<BookingStatus, 'pending'>) => { if (busy) return; setBusy(true); try { await onAction(booking.id, status); } finally { setBusy(false); } };
  return <article className="rounded-xl border border-[#1e293b] bg-[#0f172a] p-5"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-center"><div className="flex gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-full bg-[#1e293b] text-white"><UserCircle size={20} /></div><div><h2 className="font-semibold text-white">{booking.member_name || `Member #${booking.member_id}`}</h2><p className="mt-1 flex items-center gap-2 text-sm text-[#94a3b8]"><Calendar size={14} />{booking.booking_date}</p><p className="mt-1 flex items-center gap-2 text-sm text-[#94a3b8]"><Clock size={14} />{booking.start_time.slice(0, 5)}–{booking.end_time.slice(0, 5)}</p></div></div><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-3 py-1 text-xs ${tone[booking.status]}`}>{label[booking.status]}</span>{booking.status === 'pending' && <><button type="button" disabled={busy} onClick={() => void action('confirmed')} className="inline-flex items-center gap-1 rounded-lg bg-emerald-600 px-3 py-2 text-xs text-white disabled:opacity-50"><Check size={14} /> Xác nhận</button><button type="button" disabled={busy} onClick={() => void action('cancelled')} className="inline-flex items-center gap-1 rounded-lg border border-red-500/40 px-3 py-2 text-xs text-red-300 disabled:opacity-50"><X size={14} /> Hủy</button></>}{booking.status === 'confirmed' && <><button type="button" disabled={busy} onClick={() => void action('completed')} className="rounded-lg bg-blue-600 px-3 py-2 text-xs text-white disabled:opacity-50">Hoàn thành</button><button type="button" disabled={busy} onClick={() => void action('no_show')} className="rounded-lg border border-red-500/40 px-3 py-2 text-xs text-red-300 disabled:opacity-50">No-show</button><button type="button" disabled={busy} onClick={() => void action('cancelled')} className="rounded-lg border border-red-500/40 px-3 py-2 text-xs text-red-300 disabled:opacity-50">Hủy</button></>}</div></div>{booking.notes && <p className="mt-4 rounded-lg bg-[#020617] p-3 text-sm text-[#94a3b8]">{booking.notes}</p>}<Link to={`/coach/appointments/${booking.id}`} className="mt-4 inline-block text-sm text-[#60a5fa]">Xem chi tiết</Link></article>;
}

export default function CoachAppointmentsPage() {
  const [bookings, setBookings] = useState<Booking[]>([]);
  const [tab, setTab] = useState<'pending' | 'upcoming' | 'history'>('pending');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { setBookings(await getCoachAppointments({ limit: 100 })); } catch (reason: unknown) { const value = reason as { response?: { data?: { message?: string } }; message?: string }; setError(value.response?.data?.message || value.message || 'Không thể tải lịch hẹn Coach.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const visible = useMemo(() => bookings.filter(booking => tab === 'pending' ? booking.status === 'pending' : tab === 'upcoming' ? booking.status === 'confirmed' : booking.status === 'completed' || booking.status === 'cancelled' || booking.status === 'no_show'), [bookings, tab]);
  const action = async (id: number, status: Exclude<BookingStatus, 'pending'>) => { if (status === 'confirmed') await confirmBooking(id); else if (status === 'completed') await completeBooking(id); else if (status === 'no_show') await markBookingNoShow(id); else await cancelCoachBooking(id); await load(); };
  return <div className="dashboard-page"><div className="mb-8"><p className="text-sm uppercase tracking-[0.16em] text-[#60a5fa]">Coach Workspace</p><h1 className="mt-2 text-3xl font-bold text-white">Lịch hẹn học viên</h1><p className="mt-2 text-[#94a3b8]">Xử lý yêu cầu đặt lịch độc lập với lịch workout của học viên.</p></div><div className="mb-6 flex flex-wrap gap-2"><button type="button" onClick={() => setTab('pending')} className={`rounded-lg px-4 py-2 text-sm ${tab === 'pending' ? 'bg-[#2563eb] text-white' : 'bg-[#1e293b] text-[#94a3b8]'}`}>Yêu cầu mới</button><button type="button" onClick={() => setTab('upcoming')} className={`rounded-lg px-4 py-2 text-sm ${tab === 'upcoming' ? 'bg-[#2563eb] text-white' : 'bg-[#1e293b] text-[#94a3b8]'}`}>Sắp tới</button><button type="button" onClick={() => setTab('history')} className={`rounded-lg px-4 py-2 text-sm ${tab === 'history' ? 'bg-[#2563eb] text-white' : 'bg-[#1e293b] text-[#94a3b8]'}`}>Lịch sử</button></div>{loading && <div className="panel-state"><Loader2 size={18} className="mr-2 inline animate-spin" />Đang tải...</div>}{!loading && error && <div className="panel-error"><p>{error}</p><button type="button" onClick={() => void load()} className="secondary-button mt-3">Thử lại</button></div>}{!loading && !error && visible.length === 0 && <div className="panel-state">Không có lịch hẹn trong mục này.</div>}{!loading && !error && visible.length > 0 && <div className="space-y-4">{visible.map(booking => <AppointmentRow key={booking.id} booking={booking} onAction={action} />)}</div>}</div>;
}
