import {useCallback,useEffect,useMemo,useState} from "react";
import api from "../../api/axios";
type Status="PENDING"|"HELD"|"ELIGIBLE"|"PAID";
type Row={id:number;shopId:number;shopName:string;orderNumber:string;shopOrderId:number;status:Status;grossMerchandiseAmount:number;commissionAmount:number;appliedAdjustmentAmount:number;payableAmount:number;earnedAt:string;eligibleAt:string;holdReason:string|null;batchId:number|null};
const money=(value:number)=>Number(value).toLocaleString("vi-VN",{style:"currency",currency:"VND"});
const today=new Date().toISOString().slice(0,10),weekAgo=new Date(Date.now()-6*86400000).toISOString().slice(0,10);
export default function AdminSettlementsPage(){
  const [rows,setRows]=useState<Row[]>([]),[selected,setSelected]=useState<number[]>([]),[from,setFrom]=useState(weekAgo),[to,setTo]=useState(today),[status,setStatus]=useState<Status|"">(""),[search,setSearch]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{setRows((await api.get<{data:{items:Row[]}}>("/admin/marketplace-finance/settlements",{params:{from,to,status:status||undefined,search:search||undefined,pageSize:100}})).data.data.items);}catch{setError("Không thể tải settlement inbox.");}finally{setLoading(false);}},[from,to,status,search]);
  useEffect(()=>{void load();},[load]);const eligible=useMemo(()=>rows.filter(row=>row.status==="ELIGIBLE"&&!row.batchId),[rows]);
  const action=async(path:string,body:object={})=>{setError("");try{await api.post(path,body);await load();}catch(error:any){setError(error?.response?.data?.message||"Thao tác thất bại.");}};
  const hold=async(row:Row)=>{const reason=window.prompt("Lý do hold settlement");if(reason?.trim())await action(`/admin/marketplace-finance/settlements/${row.id}/hold`,{reason});};
  const release=async(row:Row)=>{const reason=window.prompt("Lý do release hold");if(reason?.trim())await action(`/admin/marketplace-finance/settlements/${row.id}/release`,{reason});};
  const adjustment=async(row:Row)=>{const raw=window.prompt("Số tiền điều chỉnh có dấu (+ tăng, - giảm)");if(!raw)return;const amount=Number(raw);const reason=window.prompt("Lý do điều chỉnh");if(!reason?.trim()||!Number.isFinite(amount)||amount===0)return;const created=(await api.post<{data:{id:number}}>("/admin/marketplace-finance/adjustments",{shopId:row.shopId,signedAmount:amount,reason,sourceShopOrderId:row.shopOrderId,sourceSettlementId:row.id})).data.data;if(window.confirm("Áp dụng điều chỉnh ngay vào settlement này?"))await action(`/admin/marketplace-finance/adjustments/${created.id}/apply`,{targetSettlementId:row.id});else await load();};
  const carryForward=async(row:Row)=>{const raw=window.prompt("Số tiền carry-forward có dấu (+ tăng, - giảm)");if(!raw)return;const signedAmount=Number(raw),reason=window.prompt("Lý do phát sinh sau PAID"),sourceReference=window.prompt("Ticket/refund/reference (không bắt buộc)")||undefined;if(!reason?.trim()||!Number.isFinite(signedAmount)||signedAmount===0)return;const created=(await api.post<{data:{id:number}}>("/admin/marketplace-finance/adjustments",{shopId:row.shopId,signedAmount,reason,sourcePaidSettlementId:row.id,sourceReference})).data.data;const target=window.prompt("Settlement tương lai cùng Shop để apply (để trống nếu chưa có)");if(target&&Number.isInteger(Number(target)))await action(`/admin/marketplace-finance/adjustments/${created.id}/apply`,{targetSettlementId:Number(target)});else await load();};
  const createBatch=async()=>{if(!selected.length)return;await action("/admin/marketplace-finance/settlement-batches",{periodStart:from,periodEnd:to,settlementIds:selected});setSelected([]);};
  const markPaid=async(row:Row)=>{if(!row.batchId)return;const reason=window.prompt("Xác nhận lý do thanh toán ngoài hệ thống");if(!reason?.trim())return;const externalReference=window.prompt("Mã tham chiếu thanh toán (không bắt buộc)")||undefined;if(window.confirm("Đánh dấu toàn bộ batch đã PAID?"))await action(`/admin/marketplace-finance/settlement-batches/${row.batchId}/mark-paid`,{reason,externalReference});};
  return <main className="space-y-5 p-4 md:p-8"><header><h1 className="text-3xl font-bold">Admin Settlement Inbox</h1><p className="text-slate-400">Đối soát thủ công; không thực hiện chuyển khoản ngân hàng.</p></header><section className="flex flex-wrap gap-3 rounded-xl border border-white/10 p-4"><input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="rounded bg-slate-900 p-2"/><input type="date" value={to} onChange={e=>setTo(e.target.value)} className="rounded bg-slate-900 p-2"/><select value={status} onChange={e=>setStatus(e.target.value as Status|"")} className="rounded bg-slate-900 p-2"><option value="">Tất cả</option><option>PENDING</option><option>HELD</option><option>ELIGIBLE</option><option>PAID</option></select><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Order / ShopOrder" className="rounded bg-slate-900 p-2"/><button className="btn-secondary" onClick={()=>void action("/admin/marketplace-finance/settlements/refresh-eligibility")}>Refresh eligibility</button><button className="btn-primary" disabled={!selected.length} onClick={()=>void createBatch()}>Tạo batch ({selected.length})</button></section>{error&&<p role="alert" className="rounded bg-red-500/10 p-3 text-red-300">{error}</p>}{loading?<p>Đang tải…</p>:rows.length===0?<p className="p-8 text-center text-slate-400">Không có settlement.</p>:<div className="overflow-x-auto rounded-xl border border-white/10"><table className="w-full min-w-[1200px]"><thead><tr><th>Chọn</th><th>Shop</th><th>Order</th><th>Gross</th><th>Commission</th><th>Adjustment</th><th>Payable</th><th>Eligible</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(row=><tr key={row.id} className="border-t border-white/10"><td className="p-3"><input type="checkbox" disabled={!eligible.some(item=>item.id===row.id)} checked={selected.includes(row.id)} onChange={e=>setSelected(value=>e.target.checked?[...value,row.id]:value.filter(id=>id!==row.id))}/></td><td>{row.shopName}</td><td>{row.orderNumber} / #{row.shopOrderId}</td><td>{money(row.grossMerchandiseAmount)}</td><td>{money(row.commissionAmount)}</td><td>{money(row.appliedAdjustmentAmount)}</td><td>{money(row.payableAmount)}</td><td>{new Date(row.eligibleAt).toLocaleDateString("vi-VN")}</td><td>{row.status}{row.holdReason&&<small className="block text-amber-300">{row.holdReason}</small>}</td><td className="space-x-2">{(row.status==="PENDING"||row.status==="ELIGIBLE")&&<button onClick={()=>void hold(row)}>Hold</button>}{row.status==="HELD"&&<button onClick={()=>void release(row)}>Release</button>}{row.status!=="PAID"&&<button onClick={()=>void adjustment(row)}>Adjustment</button>}{row.status==="PAID"&&<button onClick={()=>void carryForward(row)}>Carry-forward</button>}{row.status==="ELIGIBLE"&&row.batchId&&<button onClick={()=>void markPaid(row)}>Mark batch paid</button>}</td></tr>)}</tbody></table></div>}</main>;
}
